import { fetchAllRows } from "@/lib/admin/fetch-all-rows"
import serviceModelRanking from "@/lib/seo/service-model-ranking.json"
import type { SitemapEntry } from "@/lib/seo/sitemap-xml"
import { mainSiteUrl } from "@/lib/site-config"
import { createServerClient } from "@/utils/supabase/server"

const locales = ["uk", "cs", "en"] as const
const defaultLocale = "cs"

// Bump this whenever page templates or structured data change — that IS a real
// content change for every page the template renders (unlike a plain rebuild).
// Last bump: crawlable catalog grid on service pages, sideways model links on
// service×model pages, brand→hub chips.
const CONTENT_REVISION = new Date("2026-07-09")

// How many service×model pages we ask Google to prioritize, picked by internal
// PageRank (lib/seo/service-model-ranking.json, generated by
// scripts/link-graph/analyze.mjs --emit-ranking). The tail stays reachable and
// indexable — it is just not in the sitemap. Deliberately NO noindex on the
// tail: absence from the sitemap is reversible, noindex is slow to undo.
const SERVICE_MODEL_SITEMAP_LIMIT = 1200

export const MAIN_SITEMAP_SEGMENTS = ["core", "hubs", "services", "articles"] as const
export type MainSitemapSegment = (typeof MAIN_SITEMAP_SEGMENTS)[number]

export const MAIN_SITEMAP_LOCALES = locales
export type MainSitemapLocale = (typeof locales)[number]

export function isMainSitemapSegment(value: string): value is MainSitemapSegment {
  return (MAIN_SITEMAP_SEGMENTS as readonly string[]).includes(value)
}

export function isMainSitemapLocale(value: string): value is MainSitemapLocale {
  return (locales as readonly string[]).includes(value)
}

/**
 * The /sitemap.xml on the main host is an index of segmented files, one per
 * page type × locale. GSC then reports index coverage per segment AND per
 * locale (e.g. services-cs vs services-uk), which is exactly the monitoring
 * we need for internal-linking changes and for spotting locales Google
 * under-indexes. No lastmod here — computing it would mean building every
 * segment.
 */
export function getMainSitemapIndexEntries(): { url: string }[] {
  return MAIN_SITEMAP_SEGMENTS.flatMap((segment) =>
    locales.map((locale) => ({ url: `${mainSiteUrl}/sitemaps/${segment}-${locale}.xml` })),
  )
}

function mostRecentDate(...dates: Array<Date | null | undefined>): Date {
  const valid = dates.filter((d): d is Date => d instanceof Date && !Number.isNaN(d.getTime()))
  return valid.length ? new Date(Math.max(...valid.map((d) => d.getTime()))) : new Date()
}

const asDate = (value: unknown): Date | null => {
  if (!value) return null
  const d = new Date(String(value))
  return Number.isNaN(d.getTime()) ? null : d
}

function addMultilingualEntries(sitemapEntries: SitemapEntry[], path: string, lastModified?: Date) {
  locales.forEach((locale) => {
    const alternates: Record<string, string> = {}

    locales.forEach((altLocale) => {
      alternates[altLocale] = `${mainSiteUrl}/${altLocale}${path}`
    })

    alternates["x-default"] = `${mainSiteUrl}/${defaultLocale}${path}`

    sitemapEntries.push({
      url: `${mainSiteUrl}/${locale}${path}`,
      lastModified: lastModified ?? new Date(),
      alternates,
    })
  })
}

type PairRow = {
  serviceSlug: string
  servicePosition: number
  modelSlug: string
  modelPosition: number
  brandSlug: string | null
  seriesSlug: string | null
  // model_services.created_at — when this offer appeared. The table has no
  // updated_at, so price edits can't refresh it; CONTENT_REVISION is the floor.
  createdAt: Date | null
}

/**
 * All model_services pairs with the slugs needed to build service×model and
 * hub URLs. Paged — the table has thousands of rows and an unbounded select
 * truncates at ~1000.
 */
async function fetchPairs(supabase: Awaited<ReturnType<typeof createServerClient>>): Promise<PairRow[]> {
  const rows = await fetchAllRows<any>((from, to) =>
    supabase
      .from("model_services")
      .select("created_at, services(slug, position), models(slug, position, brands(slug), series(slug))")
      .order("model_id")
      .order("service_id")
      .range(from, to),
  ).catch((e: unknown) => {
    console.warn("[SITEMAP] Error fetching model services:", e instanceof Error ? e.message : String(e))
    return [] as any[]
  })

  const pairs: PairRow[] = []
  for (const row of rows) {
    const service = Array.isArray(row.services) ? row.services[0] : row.services
    const model = Array.isArray(row.models) ? row.models[0] : row.models
    if (!service?.slug || !model?.slug) continue
    const brand = Array.isArray(model.brands) ? model.brands[0] : model.brands
    const series = Array.isArray(model.series) ? model.series[0] : model.series
    pairs.push({
      serviceSlug: service.slug,
      servicePosition: service.position ?? 999,
      modelSlug: model.slug,
      modelPosition: model.position ?? 999,
      brandSlug: brand?.slug ? String(brand.slug).toLowerCase() : null,
      seriesSlug: series?.slug ? String(series.slug).toLowerCase() : null,
      createdAt: asDate(row.created_at),
    })
  }
  return pairs
}

/** Home, contact, brands index + brand/series/model pages + generic services. */
async function getCoreEntries(): Promise<SitemapEntry[]> {
  const supabase = await createServerClient()
  const entries: SitemapEntry[] = []

  addMultilingualEntries(entries, "")
  ;["/contact", "/brands"].forEach((page) => addMultilingualEntries(entries, page))

  const { data: brands, error: brandsError } = await supabase.from("brands").select("slug, updated_at").not("slug", "is", null)
  if (!brandsError && brands) {
    brands.forEach((brand) => {
      if (brand.slug) {
        addMultilingualEntries(
          entries,
          `/brands/${brand.slug.toLowerCase()}`,
          mostRecentDate(asDate(brand.updated_at), CONTENT_REVISION),
        )
      }
    })
  } else if (brandsError) {
    console.warn("[SITEMAP] Error fetching brands:", brandsError.message)
  }

  const { data: series, error: seriesError } = await supabase.from("series").select("slug, updated_at").not("slug", "is", null)
  if (!seriesError && series) {
    series.forEach((serie) => {
      if (serie.slug) {
        addMultilingualEntries(entries, `/series/${serie.slug}`, mostRecentDate(asDate(serie.updated_at), CONTENT_REVISION))
      }
    })
  } else if (seriesError) {
    console.warn("[SITEMAP] Error fetching series:", seriesError.message)
  }

  const { data: models, error: modelsError } = await supabase.from("models").select("slug, updated_at").not("slug", "is", null)
  if (!modelsError && models) {
    models.forEach((model) => {
      if (model.slug) {
        addMultilingualEntries(entries, `/models/${model.slug}`, mostRecentDate(asDate(model.updated_at), CONTENT_REVISION))
      }
    })
  } else if (modelsError) {
    console.warn("[SITEMAP] Error fetching models:", modelsError.message)
  }

  const { data: services, error: servicesError } = await supabase
    .from("services")
    .select("id, slug, created_at")
    .not("slug", "is", null)
  if (!servicesError && services) {
    // Only services that actually have offers: a generic service page with zero
    // model_services pairs is a thin dead-end (empty catalog grid, picker with
    // nowhere to go) — keep it out of the sitemap until it gets pairs.
    const pairs = await fetchPairs(supabase)
    const servicesWithPairs = new Set(pairs.map((p) => p.serviceSlug))
    services.forEach((service) => {
      if (!service.slug) return
      if (!servicesWithPairs.has(service.slug)) {
        console.log(`[SITEMAP] Skipping /services/${service.slug} — no model_services pairs`)
        return
      }
      addMultilingualEntries(entries, `/services/${service.slug}`, mostRecentDate(asDate(service.created_at), CONTENT_REVISION))
    })
  } else if (servicesError) {
    console.warn("[SITEMAP] Error fetching services:", servicesError.message)
  }

  return entries
}

/** Brand×service + series×service hub pages, lastmod = newest member offer. */
async function getHubEntries(): Promise<SitemapEntry[]> {
  const supabase = await createServerClient()
  const entries: SitemapEntry[] = []
  const pairs = await fetchPairs(supabase)

  const brandHubs = new Map<string, Date | null>()
  const seriesHubs = new Map<string, Date | null>()
  const newer = (current: Date | null | undefined, next: Date | null) =>
    !current || (next && next.getTime() > current.getTime()) ? next : current

  for (const pair of pairs) {
    if (pair.brandSlug) {
      const key = `/services/${pair.serviceSlug}/brand/${pair.brandSlug}`
      brandHubs.set(key, newer(brandHubs.get(key), pair.createdAt))
    }
    if (pair.seriesSlug) {
      const key = `/services/${pair.serviceSlug}/series/${pair.seriesSlug}`
      seriesHubs.set(key, newer(seriesHubs.get(key), pair.createdAt))
    }
  }

  for (const [path, newest] of brandHubs) addMultilingualEntries(entries, path, mostRecentDate(newest, CONTENT_REVISION))
  for (const [path, newest] of seriesHubs) addMultilingualEntries(entries, path, mostRecentDate(newest, CONTENT_REVISION))
  console.log(`[SITEMAP] hubs segment: ${brandHubs.size} brand hubs + ${seriesHubs.size} series hubs`)
  return entries
}

/**
 * Top-N service×model money pages by INTERNAL PageRank — the best-linked pages
 * are the ones we ask Google to prioritize, so our sitemap signal agrees with
 * the link graph instead of contradicting it. Ranked pairs that no longer
 * exist are dropped; if fewer than N ranked pairs are live (stale ranking,
 * new catalog), the rest is filled by admin-curated position order.
 */
async function getServiceModelEntries(): Promise<SitemapEntry[]> {
  const supabase = await createServerClient()
  const entries: SitemapEntry[] = []
  const pairs = await fetchPairs(supabase)

  const byKey = new Map(pairs.map((p) => [`${p.serviceSlug}|${p.modelSlug}`, p]))
  const picked: PairRow[] = []
  const seen = new Set<string>()

  const ranked: Array<{ s: string; m: string }> = (serviceModelRanking as any)?.pairs ?? []
  for (const r of ranked) {
    if (picked.length >= SERVICE_MODEL_SITEMAP_LIMIT) break
    const key = `${r.s}|${r.m}`
    const pair = byKey.get(key)
    if (pair && !seen.has(key)) {
      seen.add(key)
      picked.push(pair)
    }
  }

  if (picked.length < SERVICE_MODEL_SITEMAP_LIMIT) {
    const fill = pairs
      .filter((p) => !seen.has(`${p.serviceSlug}|${p.modelSlug}`))
      .sort(
        (a, b) =>
          a.servicePosition - b.servicePosition ||
          a.modelPosition - b.modelPosition ||
          a.serviceSlug.localeCompare(b.serviceSlug) ||
          a.modelSlug.localeCompare(b.modelSlug),
      )
    for (const pair of fill) {
      if (picked.length >= SERVICE_MODEL_SITEMAP_LIMIT) break
      picked.push(pair)
    }
  }

  for (const pair of picked) {
    addMultilingualEntries(entries, `/services/${pair.serviceSlug}/${pair.modelSlug}`, mostRecentDate(pair.createdAt, CONTENT_REVISION))
  }
  console.log(`[SITEMAP] services segment: ${picked.length}/${pairs.length} service×model pages (limit ${SERVICE_MODEL_SITEMAP_LIMIT})`)
  return entries
}

/** Articles index + published article pages (per-locale translation slugs). */
async function getArticleEntries(): Promise<SitemapEntry[]> {
  const supabase = await createServerClient()
  const entries: SitemapEntry[] = []

  addMultilingualEntries(entries, "/articles")

  const { data: articleTranslations, error: articlesError } = await supabase
    .from("article_translations")
    .select("article_id, slug, locale, updated_at, articles(updated_at, published)")
    .eq("articles.published", true)
    .not("slug", "is", null)

  if (!articlesError && articleTranslations) {
    const processedArticles = new Set<string>()

    articleTranslations.forEach((translation: any) => {
      const articleId = translation.article_id
      if (processedArticles.has(articleId)) return

      const allTranslations = articleTranslations.filter((item: any) => item.article_id === articleId)
      const alternates: Record<string, string> = {}

      allTranslations.forEach((item: any) => {
        alternates[item.locale] = `${mainSiteUrl}/${item.locale}/articles/${item.slug}`
      })

      alternates["x-default"] =
        `${mainSiteUrl}/${defaultLocale}/articles/${allTranslations.find((item: any) => item.locale === defaultLocale)?.slug || allTranslations[0].slug}`

      allTranslations.forEach((item: any) => {
        entries.push({
          url: `${mainSiteUrl}/${item.locale}/articles/${item.slug}`,
          lastModified: asDate(item.updated_at) ?? new Date(),
          alternates,
        })
      })

      processedArticles.add(articleId)
    })
  } else if (articlesError) {
    console.warn("[SITEMAP] Error fetching articles:", articlesError.message)
  }

  return entries
}

export async function getMainSitemapSegmentEntries(
  segment: MainSitemapSegment,
  locale?: MainSitemapLocale,
): Promise<SitemapEntry[]> {
  try {
    let entries: SitemapEntry[]
    switch (segment) {
      case "core":
        entries = await getCoreEntries()
        break
      case "hubs":
        entries = await getHubEntries()
        break
      case "services":
        entries = await getServiceModelEntries()
        break
      case "articles":
        entries = await getArticleEntries()
        break
    }
    if (!locale) return entries
    // Per-locale sitemap file: keep only this locale's URLs. Entries keep the
    // full hreflang alternate set — cross-file alternates are valid.
    const base = `${mainSiteUrl}/${locale}`
    return entries.filter((entry) => entry.url === base || entry.url.startsWith(`${base}/`))
  } catch (error) {
    console.error(`[SITEMAP] Error generating '${segment}' segment:`, error)
    return []
  }
}

/** All segments concatenated — kept for consumers that need the full universe. */
export async function getMainSitemapEntries(): Promise<SitemapEntry[]> {
  const segments = await Promise.all(MAIN_SITEMAP_SEGMENTS.map((segment) => getMainSitemapSegmentEntries(segment)))
  return segments.flat()
}
