"use client"

import { useTranslations } from "next-intl"

export default function PrivacyPage() {
  const t = useTranslations("Privacy")

  return (
    <div className="container mx-auto px-4 py-12">
      <div className="mb-8 text-center">
        <h1 className="text-4xl font-bold">{t("title")}</h1>
      </div>

      <div className="prose prose-sm sm:prose lg:prose-lg mx-auto">
        {/# Politika zpracování osobních údajů

## Základní shrnutí
Tato politika vysvětluje, jakým způsobem zpracováváme Vaše osobní údaje v souvislosti s provozem webu **devicehelp.cz** a poskytováním našich služeb (opravy mobilních telefonů). Dozvíte se, jaké údaje shromažďujeme, proč je potřebujeme, komu je případně předáváme (např. našim partnerům **RemOnline**, **Vercel**, **Google Ads**, **Facebook Pixel**) a jaká máte **práva** podle GDPR. Osobní údaje chráníme v souladu s platnými právními předpisy (GDPR a české zákony) a používáme je pouze k stanoveným účelům. Web využívá soubory **cookies** pro nutné fungování stránek a s Vaším souhlasem také pro analytiku a marketing – podrobnosti o cookies najdete níže. Prosíme, pečlivě si tuto Politiku přečtěte; obsahuje důležité informace o ochraně Vašeho soukromí.

## Správce osobních údajů a kontaktní údaje
- **Správce (provozovatel webu)**: Yevhenii Palapa, IČO: 21725209  
- **Sídlo**: Bělohorská 209/133, 169 00 Praha 6-Břevnov, 169 00, Česká republika  
- **Kontaktní e-mail**: info@devicehelp.cz  
- **Telefon**: +420 775 848 259  

Správce je fyzická osoba podnikající, která provozuje webové stránky devicehelp.cz a poskytuje servis mobilních telefonů pod uvedenými identifikačními údaji. Správce **nejmenoval pověřence pro ochranu osobních údajů** (DPO), neboť mu to dle GDPR nevzniká jako povinnost. Veškeré dotazy či žádosti týkající se zpracování osobních údajů směřujte prosím na výše uvedený e-mail či adresu správce.

## Získávání a kategorie zpracovávaných osobních údajů
Zpracováváme pouze takové osobní údaje, které nám sami poskytnete nebo které získáme v rámci poskytování našich služeb. Nejčastěji nám údaje předáte při **registraci na webu**, **zadání objednávky opravy** (online i offline) nebo při komunikaci s námi (např. e-mailem či telefonicky). Konkrétně můžeme zpracovávat tyto kategorie osobních údajů:

- **Identifikační údaje**: jméno a příjmení; případně název firmy a IČ (pokud jednáte jako podnikatel).
- **Kontaktní údaje**: e-mailová adresa; telefonní číslo; poštovní adresa (ulice, město, PSČ) pokud je potřebná např. pro zaslání zařízení či fakturaci.
- **Údaje pro registraci**: přihlašovací jméno (uživatelské jméno nebo e-mail) a heslo (uložené v bezpečně zahashované podobě) pro vytvoření uživatelského účtu.
- **Údaje o objednávce a servisu**: informace o Vámi poptávané či objednané opravě zařízení – např. typ zařízení, popis závady, sériové číslo zařízení (pokud je uvedeno), datum objednání opravy, stav a historie zakázky, případně doplňující informace, které nám poskytnete (např. fotografie zařízení, poznámky).
- **Platební a fakturační údaje**: pokud dojde k placení za služby, můžeme zpracovat údaje na faktuře (např. fakturační adresu) a informace o přijaté platbě. **Poznámka:** Čísla platebních karet ani jiné citlivé platební údaje neshromažďujeme – platby probíhají přes zabezpečené platební brány třetích stran, my obdržíme jen potvrzení o platbě.
- **Komunikační údaje**: obsah naší komunikace (e-mailová korespondence, záznamy telefonických dotazů, chatová historie, pokud je k dispozici zákaznický chat). Tyto údaje evidujeme pro vyřízení Vašich požadavků a zlepšení služeb.
- **Technické údaje o návštěvě webu**: IP adresa zařízení, ze kterého přistupujete; soubory cookies (viz níže samostatná sekce o cookies); případně další online identifikátory (např. údaje o prohlížeči, operačním systému, rozlišení obrazovky). Tyto technické informace získáváme automaticky při Vaší návštěvě webu pomocí našeho systému a skriptů třetích stran (Google, Facebook), a slouží nám k zajištění správného fungování webu a analytickým účelům.

**Údaje z offline objednávek**: Pokud objednáte opravu **offline** (například osobně v naší provozovně nebo telefonicky), požádáme Vás o poskytnutí potřebných osobních údajů (typicky jméno, kontakt a informace o zařízení). Tyto údaje poté **zadáme do našeho interního systému** (RemOnline) a **vytvoříme Vám uživatelský účet**, abychom mohli Vaši zakázku spravovat stejně, jako byste ji zadal online. Díky tomu budete moci svou zakázku případně sledovat či spravovat i přes náš web. Veškeré takto získané údaje z offline zakázky zpracováváme podle této politiky stejným způsobem, jako byste je vyplnil na webu.

Správce nezpracovává žádné **citlivé osobní údaje** ve smyslu čl. 9 GDPR (tj. údaje o zdravotním stavu, biometrické údaje, údaje o trestních deliktech apod.), ledaže byste je výjimečně sám dobrovolně sdělil v komunikaci (což však neočekáváme, a pokud by k tomu došlo, takové informace nevyužíváme a případně je vymažeme).

## Účely zpracování a právní základy
Vaše osobní údaje zpracováváme **výhradně k legitimním účelům**, a to na základě některého z **právních titulů** podle čl. 6 GDPR. Konkrétně můžeme Vaše údaje použít k těmto účelům:

1. **Poskytování našich služeb a plnění smlouvy:** Údaje zpracováváme především proto, abychom Vám mohli **vyřídit Vaši objednávku opravy** a obecně poskytovat dohodnuté služby. To zahrnuje zejména přijetí a evidenci zakázky, komunikaci ohledně stavu opravy, samotné provedení opravy zařízení, vystavení servisního protokolu a faktury, řešení případných reklamací apod. Právním základem je **plnění smlouvy** dle čl. 6 odst. 1 písm. b) GDPR – bez poskytnutí těchto údajů bychom nemohli smlouvu (zakázku) uzavřít ani splnit. Sem spadá i **správa uživatelského účtu** na webu – pokud si u nás zaregistrujete účet (nebo Vám jej vytvoříme k offline zakázce), zpracováváme Vaše registrační údaje, abychom Vám umožnili bezpečný přístup k účtu a funkčnost účtu (právní základ také plnění smlouvy, resp. v případě samotné registrace lze považovat založení a vedení účtu za službu, kterou Vám poskytujeme).
2. **Komunikace s Vámi a zákaznická podpora:** Vaše kontaktní údaje a obsah komunikace využíváme k tomu, abychom s Vámi mohli **komunikovat** – například odpovědět na dotaz zaslaný přes web nebo e-mail, potvrdit přijetí objednávky, konzultovat rozsah opravy, informovat o dokončení servisu, zaslat podklady k platbě apod. Právním důvodem je opět **plnění smlouvy** (pokud jde o komunikaci týkající se konkrétní zakázky či smlouvy) nebo **oprávněný zájem** správce poskytovat kvalitní služby a reagovat na Vaše podněty (čl. 6 odst. 1 písm. f) GDPR) – v případě obecných dotazů ještě před uzavřením smlouvy lze komunikaci považovat též za **opatření před uzavřením smlouvy** na Vaši žádost (také spadá pod čl. 6 odst. 1 písm. b) GDPR).
3. **Splnění právních povinností:** Některé Vaše údaje musíme zpracovat také z důvodu plnění našich **právních povinností**. Jde zejména o povinnosti vyplývající z účetních a daňových zákonů – např. uchování faktur a evidenci pro účetnictví, plnění povinností podle zákona o DPH, zákona o účetnictví apod. Dále sem spadá případné poskytování součinnosti orgánům veřejné moci, pokud by nás například policie či jiný úřad vyzval k předání konkrétních údajů v souladu se zákonem. Právním základem zpracování je v takových případech **plnění právní povinnosti** správce dle čl. 6 odst. 1 písm. c) GDPR.
4. **Vylepšování našich služeb a provoz webu:** Abychom mohli náš web a služby udržovat a zlepšovat, můžeme provádět **analýzy návštěvnosti a uživatelského chování** na webu, testovat nová vylepšení apod. K tomu využíváme především agregované a anonymizované údaje (např. statistiky návštěvnosti), případně pseudonymizované údaje z cookies a analytických nástrojů. V minimální míře využíváme technické údaje (cookies) nezbytné pro samotný **provoz webu** – například k udržení Vaší přihlášené relace, zapamatování nastavení jazyka apod. Právním titulem pro zpracování nezbytných technických údajů je náš **oprávněný zájem** na zajištění funkčnosti a bezpečnosti webu (čl. 6 odst. 1 písm. f) GDPR). Pokud jde o nadstandardní analytické nástroje (viz cookies níže), opíráme se o **souhlas** uživatele (čl. 6 odst. 1 písm. a) GDPR), aby bylo zajištěno respektování Vašeho práva na soukromí (tj. nepoužíváme nepotřebné cookies/trackery bez Vašeho svolení).
5. **Marketingové účely a zasílání obchodních sdělení:** Vaše identifikační a kontaktní údaje můžeme využít také k **marketingu našich služeb** – typicky k zaslání e-mailového oznámení o našich novinkách, slevách či službách, které by Vás mohly zajímat (**obchodní sdělení** či newsletter). Tyto materiály Vám budeme zasílat pouze přiměřeně (občasně) a **vždy máte možnost se z odběru odhlásit**. Pokud jste naším zákazníkem (např. jste u nás již využil opravárenské služby), dovoluje nám zákon č. 480/2004 Sb., o některých službách informační společnosti, zasílat Vám obchodní sdělení na e-mail, který jste poskytl, **i bez Vašeho předchozího souhlasu**, jelikož jde o tzv. oprávněný zájem správce (čl. 6 odst. 1 písm. f) GDPR) na přímém marketingu vůči svým zákazníkům (§ 7 odst. 3 cit. zákona). Samozřejmě i v takovém případě máte možnost kdykoli další marketingové e-maily **odmítnout** (opt-out) – v každém e-mailu bude odkaz pro odhlášení. Pokud **nejste naším zákazníkem** a přesto byste chtěl newsletter dostávat, budeme tak činit pouze, pokud nám k tomu **udělíte souhlas** (např. registrací k odběru novinek). K marketingu patří i využití cookies třetích stran pro **cílení reklamy** (Google/Facebook) – to provádíme jen, pokud k tomu dáte souhlas (viz dále).
6. **Online reklama a personalizace nabídky:** Na našem webu máme nasazené marketingové nástroje (**Google Ads**, **Facebook Pixel**), které nám pomáhají zobrazovat Vám reklamy na naše služby na jiných platformách (např. reklamy Google při vyhledávání, či reklamy na Facebooku) – jedná se o tzv. **remarketing**. Tyto nástroje využívají soubory cookies a podobné technologie ke sledování, jak jste náš web použil, které stránky jste navštívil, zda jste odeslal poptávku apod. Na základě toho můžeme pak vytvořit skupiny uživatelů pro cílení reklam (např. oslovit uživatele, kteří navštívili naši stránku s určitým modelem telefonu). Právním základem pro toto sledování a zpracování je **Váš souhlas** s cookies (čl. 6 odst. 1 písm. a) GDPR), jelikož nejde o nezbytné zpracování. Bez Vašeho souhlasu nebudou tyto marketingové cookies aktivní. Podrobnosti o fungování cookies a možnostech souhlasu viz sekce níže.

Správce **nepoužívá osobní údaje k automatizovanému individuálnímu rozhodování**, které by pro Vás mělo právní účinky nebo se Vás obdobně významně dotýkalo, ve smyslu čl. 22 GDPR. Veškeré zpracování probíhá buď manuálně našimi pracovníky, nebo sice automatizovaně (v rámci IT systémů), ale **bez** právně významných účinků pro subjekt údajů. Profilování uživatelů pro účely cílení reklamy (viz výše marketingové cookies) probíhá jen na obecné úrovni skupin návštěvníků a **nezakládá vůči Vám žádné rozhodnutí** či závazek – slouží pouze k přizpůsobení marketingu.

## Soubory cookies a webová analytika
**Cookies** jsou malé textové soubory, které se ukládají do Vašeho zařízení (počítače, telefonu) při návštěvě webových stránek. My a námi využívané třetí strany používáme cookies k odlišným účelům. Některé cookies jsou **technicky nezbytné** pro správné fungování webu – ty ukládáme automaticky, jakmile na náš web vstoupíte (nevyžadují souhlas). Jiné cookies nám pomáhají web **vylepšovat** (analytické cookies) nebo Vám zobrazovat **personalizované reklamy** i mimo naše stránky (marketingové cookies); tyto tzv. **volitelné cookies** však ukládáme pouze, pokud nám k tomu udělíte souhlas v rámci cookie lišty při Vaší první návštěvě.

Na našem webu používáme zejména tyto typy cookies a nástrojů:

- **Nezbytné (technické) cookies:** Tyto cookies zajišťují základní provoz a bezpečnost stránek. Umožňují například udržet Vás přihlášeného po dobu návštěvy (session cookie), zapamatovat si obsah Vaší poptávky, přepínat vzhled nebo jazyk webu apod. Bez těchto cookies by web nemohl správně fungovat, proto jsou ukládány automaticky. Nezbytné cookies si pamatují pouze minimální informace a nejsou využívány k marketingu. Patří sem i cookies platformy **Vercel** (na které je web provozován) pro směrování požadavků a udržení stability služeb.
- **Analytické cookies:** S jejich pomocí sledujeme, jak si náš web vede – například počet návštěvníků, odkud návštěvníci přicházejí, jaké stránky jsou nejčtenější, jak dlouho se zdrží, případně zda při procházení webem narazili na chybu. K tomu využíváme nástroje třetích stran, zejména **Google** (např. Google Analytics nebo obdobnou funkci v rámci Google Ads). Tyto cookies mohou zaznamenávat Vaši IP adresu, údaje o zařízení a prohlížeči, a pohyb po našich stránkách. Data, která takto získáme, používáme ve statistické podobě (např. celkový počet návštěv, demografický přehled návštěvníků) k tomu, abychom vylepšili obsah a funkce webu. Nastavení těchto cookies je **volitelné** – při první návštěvě webu Vám zobrazíme lištu s možností přijmout či odmítnout analytické cookies. Pokud odmítnete, nebudeme je ukládat a základní fungování webu tím nebude omezeno.
- **Marketingové cookies (reklamní sledovací pixely):** Na webu jsou integrovány nástroje **Google Ads** (Google Ireland Ltd.) a **Facebook Pixel** (Meta Platforms Ireland Ltd.), které nám umožňují marketingové aktivity popsané výše. Tyto nástroje ukládají cookies nebo používají podobné technologie k tomu, aby rozpoznaly Vaše zařízení při návštěvě našich stránek a následně Vám pomohly zobrazit cílené reklamy. Marketingové cookies sbírají informace o Vaší návštěvě (např. které stránky jste navštívil, na co jste klikl, případně zda jste provedl konverzi/odeslal formulář). Tyto informace jsou odesílány příslušné třetí straně (Google, Facebook), která je zpracovává podle svých zásad ochrany soukromí. My získáváme přístup jen k agregovaným datům (např. kolik uživatelů kliklo na naši reklamu) a případně k anonymnímu identifikátoru Vaší návštěvy. Marketingové cookies používáme **pouze na základě Vašeho souhlasu**. Pokud je při vstupu na web odmítnete, nebudou tyto pixely aktivní a žádná data se nepředají. Pokud je přijmete, vždy lze svůj souhlas později **odvolat** – buď změnou nastavení cookies na našem webu (např. přes odkaz „Nastavení cookies“) nebo vymazáním/úpravou nastavení cookies ve Vašem prohlížeči (viz dále).

**Doba uchování cookies:** Některé cookies (session cookies) jsou dočasné a smažou se po zavření prohlížeče. Jiné mají tzv. expirační dobu – například Google Analytics cookie může přetrvat až 2 roky, Facebook pixel identifikátor zpravidla několik měsíců. Konkrétní přehled cookies a jejich platnosti najdete v nastavení cookies na našem webu (případně v informacích přímo od Google/Facebook). 

**Správa cookies:** Kromě úvodní volby na naší stránce můžete používání cookies ovlivnit nastavením Vašeho **internetového prohlížeče**. V nastavení prohlížeče můžete již uložené cookies vymazat a zakázat ukládání cookies (všech nebo jen některých typů). Berte ovšem na vědomí, že pokud zakážete i nezbytné cookies, nemusí web fungovat korektně a některé funkce (např. přihlášení, obsah košíku či formulářů) se Vám mohou rozbít. Většina prohlížečů také nabízí možnost blokovat cookies třetích stran (cookies, které nejsou z naší domény). Pro úplnost dodáváme, že pokud odmítnete naše volitelné cookies, web bude nadále plně přístupný, pouze se k Vám nedostanou některé personalizované funkce či reklamy.

## Předávání osobních údajů třetím stranám
K Vašim osobním údajům mají přístup **především naši pověření pracovníci** (provozovatel a případně omezený okruh spolupracovníků zajišťujících servis či administrativu), a to jen v nezbytné míře pro plnění svých úkolů. Kromě toho využíváme několik **důvěryhodných třetích stran**, kterým Vaše údaje můžeme zpřístupnit, pokud je to nutné pro zajištění našich služeb a provozu webu. Se všemi takovými subjekty máme uzavřeny odpovídající smlouvy o zpracování údajů dle čl. 28 GDPR, případně vystupují jako samostatní správci s vlastní odpovědností (např. Google, Facebook). Konkrétně může docházet k předání údajů těmto kategoriím příjemců:

- **Poskytovatel systému pro správu zakázek – RemOnline:** Pro evidenci a řízení servisních objednávek využíváme online software RemOnline (cloudový servisní systém). **RemOnline** pro nás funguje jako **zpracovatel** – osobní údaje zákazníků (kontaktní a identifikační údaje, údaje o zařízení a zakázce) jsou ukládány na jejich zabezpečených serverech. Tento systém nám umožňuje efektivně spravovat Vaši zakázku od přijetí až po vyřízení. RemOnline může mít přístup k datům pouze za účelem údržby a technické podpory systému, nikoli k vlastnímu využití dat. (Pozn.: RemOnline je provozován zahraniční společností – data mohou být uložena mimo ČR, avšak dle poskytovatele v souladu s evropskými předpisy o ochraně dat.)
- **Provozovatel hostingové platformy – Vercel:** Náš web je umístěn na platformě **Vercel**. Vercel (Vercel Inc.) zajišťuje hosting a provozní infrastrukturu pro naše stránky. Osobní údaje, které na webu vyplníte (např. registrační formulář), tak procházejí servery Vercel a mohou být dočasně uloženy v jejich systému (např. v databázi či log souborech). Vercel vystupuje jako **zpracovatel** a je smluvně zavázán chránit data dle GDPR. Upozorňujeme, že Vercel je společnost se sídlem v USA – může tedy docházet k **přenosu dat do USA**. Takový přenos je legální díky standardním smluvním doložkám a dalším zárukám, které máme s Vercel sjednány, popř. díky certifikaci v rámci tzv. EU–US Data Privacy Framework (pokud je společnost Vercel certifikována). Tyto mechanismy zajišťují, že i v USA jsou Vaše data v bezpečí srovnatelném s EU standardy.
- **Poskytovatelé marketingových a analytických služeb – Google a Meta (Facebook):** Jak bylo zmíněno, využíváme služby **Google Ads** (pro online reklamu, případně měření konverzí) a případně **Google Analytics** (pro analýzu návštěvnosti), které poskytuje společnost Google Ireland Limited (se sídlem v EU, avšak data mohou být následně zpracovávána i společností Google LLC v USA). Dále používáme službu **Facebook Pixel** od společnosti Meta Platforms Ireland Ltd. (Facebook) pro marketing a analytiku. Tyto společnosti vystupují jako **samostatní správci** pro data, která prostřednictvím jejich cookies shromažďují – např. Google využívá data o návštěvnosti ke svým vlastním účelům (zlepšování svých služeb, personalizace prostředí Google apod.). My nemáme přístup k Vašim osobním údajům, které Google či Facebook získají pro své potřeby – máme jen souhrnné výstupy. Každopádně tím, že máme jejich nástroje na našem webu, dochází k **předání některých údajů o uživateli těmto třetím stranám**. Může jít o IP adresu, identifikátory cookies, údaje o Vašem zařízení a akce na webu. K předání dochází pouze, pokud jste nám udělili souhlas s příslušnými cookies. Google i Meta zajišťují ochranu dat v souladu s GDPR – využívají standardní smluvní doložky pro přenos do USA a technická opatření k ochraně dat (navíc Google i Meta jsou součástí schváleného programu EU–US Data Privacy Framework). Další informace o zpracování dat těmito subjekty naleznete v jejich vlastních zásadách (Google Privacy Policy, Facebook Data Policy).
- **Další dodavatelé a poradci:** V případě potřeby můžeme využít i služeb dalších dodavatelů, kteří mohou při své činnosti přijít do styku s některými údaji – například externí účetní firma (pokud zpracovává naše účetnictví včetně faktur s Vašimi údaji), IT servis a podpora (při řešení technických problémů se může odborník dostat k databázi), právní zástupce (např. v případě vymáhání pohledávek či řešení sporu). S každým takovým subjektem máme uzavřenu smlouvu o mlčenlivosti a případně o zpracování údajů, aby Vaše data byla chráněna. Tito příjemci smí data využít jen k poskytnutí dané služby nám, nikoli pro své vlastní účely.
- **Orgány veřejné moci:** Pokud by to vyžadoval zákon nebo závazné rozhodnutí orgánu veřejné správy (např. soudního nebo dozorového úřadu), můžeme Vaše osobní údaje poskytnout těmto orgánům. Typicky by šlo o situace, kdy bychom byli povinni vydat údaje na základě zákona (např. na vyžádání policie při vyšetřování trestného činu, nebo při kontrole Úřadu pro ochranu osobních údajů). V takových případech poskytujeme jen data, která daný orgán požaduje a k nimž má zákonné oprávnění.

**Nepředáváme Vaše osobní údaje žádným třetím stranám** za účelem jejich vlastního marketingu či obchodování. Nikdy neprodáváme Vaše data žádným zprostředkovatelům databází. Veškeré sdílení údajů se děje pouze za účelem zajištění našich služeb směrem k Vám, případně plnění zákona.

Při jakémkoli předání osobních údajů dbáme na dodržení principu minimalizace – třetí strany obdrží jen ty údaje, které skutečně potřebují pro výkon své role. Všichni zpracovatelé jsou vázáni smluvně zpracovávat data pouze podle našich pokynů a chránit je. Pokud by v budoucnu přibyli další příjemci, budeme Vás o tom informovat aktualizací této politiky.

## Doba uložení osobních údajů
Osobní údaje uchováváme **pouze po nezbytně dlouhou dobu**, která je individuální podle účelu zpracování. Průběžně vyhodnocujeme, zda určité údaje stále potřebujeme, a pokud ne, bezpečně je vymažeme či anonymizujeme. Níže uvádíme obecné lhůty uchování pro hlavní účely zpracování:

- **Údaje o zákaznících a zakázkách (plnění smlouvy):** Vaše identifikační, kontaktní a objednávkové údaje související s konkrétní opravou uchováváme po dobu trvání smluvního vztahu (realizace zakázky) a následně **po dobu 10 let od dokončení zakázky**. Tato doba vychází z doby, po kterou mohou vznikat případné nároky z vadného plnění či jiné právní nároky (standardní promlčecí lhůty jsou 3 roky, ale některé doklady musíme uchovávat déle podle zákona – viz níže, a pro jistotu evidence historie servisu volíme 10letou lhůtu). Pokud by se jednalo o dlouhodobé zákaznické konto s více zakázkami, lhůta 10 let běží od poslední realizované zakázky. Po uplynutí této doby Vaše zákaznické údaje z aktivní databáze vymažeme nebo archivujeme v omezeném rozsahu, pokud by to bylo nutné (např. evidenční listiny).
- **Účetní a daňové doklady:** Faktury a záznamy o platbách, které obsahují Vaše osobní údaje (jméno, adresu, případně další náležitosti), jsme povinni uchovávat podle zákona o účetnictví a daňových předpisů **po dobu 5 až 10 let** od jejich vystavení. Tyto doklady archivujeme odděleně v zabezpečeném archivu. Po uplynutí zákonných lhůt je vyřazujeme/skartujeme.
- **Uživatelský účet na webu:** Údaje spojené s Vaším uživatelským účtem (registrace) uchováváme po dobu, po kterou je účet aktivní. Pokud svůj účet **zrušíte** (nebo nás požádáte o výmaz), smažeme nebo anonymizujeme veškeré osobní údaje k účtu, vyjma údajů, které musíme dále uchovat z jiných zákonných důvodů (např. zachování záznamů o provedených objednávkách, viz výše). Pokud bude Váš účet neaktivní (např. nepřihlásíte se po velmi dlouhou dobu), můžeme Vás upozornit a účet případně smazat, abychom údaje dále zbytečně nedrželi.
- **Komunikace a podpora:** E-mailovou komunikaci a záznamy o telefonních hovorech uchováváme zpravidla **po dobu 2 let**, pro vnitřní potřeby evidence a zlepšování služeb. Pokud jde o komunikaci související s konkrétní smlouvou nebo řešením reklamace, můžeme ji uchovat po stejnou dobu jako ostatní údaje o zakázce (viz výše 10 let), pro případ obrany našich práv.
- **Marketingové seznamy:** Pokud zpracováváme Vaše údaje pro zasílání newsletteru na základě souhlasu, činíme tak **do odvolání souhlasu**, nejdéle však po dobu 5 let od udělení souhlasu nebo od poslední interakce. Po uplynutí této doby Vás požádáme o obnovení souhlasu, jinak údaje vyřadíme z marketingového seznamu. U zákazníků, kterým posíláme obchodní sdělení na základě oprávněného zájmu, budeme e-maily zasílat, dokud budete naším zákazníkem a dále cca 3 roky poté (nebo dříve, pokud sdělíte, že už nemáte zájem). Vždy máte možnost snadno další marketing odhlásit.
- **Cookies:** Doba uchování dat z cookies se liší dle typu (viz sekce o cookies). Technické cookies pro fungování webu jsou uloženy jen po dobu návštěvy či krátce poté; analytické a marketingové cookies mohou přetrvávat několik měsíců až 2 roky, pokud je nevymažete. Podrobnosti jsou uvedeny u jednotlivých cookies. Můžete také kdykoli cookies vymazat z Vašeho prohlížeče – tím se i jimi shromážděná data na Vašem zařízení odstraní. Data získaná třetími stranami (Google, Facebook) jsou u nich uchovávána dle jejich zásad – např. Google Analytics údaje 14 měsíců apod.

Po uplynutí příslušných lhůt provádíme výmaz či anonymizaci osobních údajů. Anonymizace znamená, že data již nelze spojit s konkrétní osobou (např. agregované statistiky). Upozorňujeme, že v případě, kdy uplatníte právo na výmaz, můžeme mít přesto povinnost některé údaje nadále uchovat (např. fakturu dle zákona), ale tyto údaje pak již nebudou využity k jiným účelům.

## Vaše práva v souvislosti se zpracováním osobních údajů
Jako **subjekt údajů** máte řadu práv, kterými můžete ovlivnit, jak nakládáme s Vašimi osobními údaji. Vaše práva vyplývají zejména z kapitoly III GDPR (čl. 12 až 22 GDPR). Konkrétně máte následující práva:

- **Právo na přístup k osobním údajům (čl. 15 GDPR):** Máte právo od nás získat potvrzení, zda zpracováváme Vaše osobní údaje, a pokud ano, právo získat kopii těchto údajů a informace o tom, jak údaje zpracováváme. Zjednodušeně můžete požádat o přehled Vašich osobních údajů v naší evidenci.
- **Právo na opravu (čl. 16 GDPR):** Pokud zjistíte, že o Vás evidujeme neaktuální nebo nepřesné údaje (například špatně zapsané jméno, překlep v e-mailu apod.), máte právo požadovat jejich **opravu či doplnění**. Budeme rádi, když nás na takovou skutečnost upozorníte, abychom udržovali data správná.
- **Právo na výmaz („právo být zapomenut“) (čl. 17 GDPR):** Za určitých okolností máte právo požadovat, abychom Vaše osobní údaje vymazali. Můžete tak učinit například, pokud údaje již nejsou potřebné pro účely, pro které byly shromážděny, nebo pokud odvoláte souhlas a my nemáme jiný právní důvod pro zpracování, nebo vznese-li úspěšně námitku proti zpracování (viz níže), případně pokud by byly údaje zpracovávány protiprávně. Mějte však na paměti, že právo na výmaz není absolutní – v některých případech nemůžeme údaje vymazat z důvodu naší zákonné povinnosti či ochrany našich oprávněných zájmů (např. musíme-li dle zákona uchovat faktury, nemůžeme je na Vaši žádost smazat; podobně si můžeme ponechat základní údaje o smlouvě, dokud neuplynou promlčecí lhůty pro případnou obranu).
- **Právo na omezení zpracování (čl. 18 GDPR):** Toto právo Vám umožňuje v určitých situacích žádat, abychom dočasně **omezili zpracování** Vašich osobních údajů. Jde například o případy, kdy popíráte přesnost údajů (na dobu, než ověříme přesnost), nebo když namítáte proti zpracování (na dobu, než ověříme, zda naše oprávněné důvody převažují nad Vašimi), případně když je zpracování protiprávní, ale nechcete data smazat a raději požadujete jen omezení jejich použití. Při omezení zpracování smíme dotčené údaje jen uložit a jinak je zpracovávat pouze s Vaším souhlasem nebo z důvodů stanovených zákonem.
- **Právo vznést námitku (čl. 21 GDPR):** Pokud zpracováváme Vaše osobní údaje na základě **oprávněného zájmu**, máte právo kdykoli **vznést námitku** proti takovému zpracování. Poté již Vaše údaje nesmíme dále pro daný účel zpracovávat, ledaže prokážeme závažné oprávněné důvody, které převažují nad Vašimi právy a svobodami (což v praxi posoudíme). Pokud vznesete námitku proti zpracování pro účely **přímého marketingu**, přestaneme Vaše údaje k tomuto účelu využívat vždy – zde není potřeba nic dalšího prokazovat (námitka v případě marketingu je absolutně závazná). Námitku lze podat například proti zasílání newsletteru (poté ihned zastavíme zasílání) nebo proti analytickému sledování (pokud by probíhalo na základě oprávněného zájmu – v našem případě však analytiku provádíme jen s Vaším souhlasem).
- **Právo na přenositelnost údajů (čl. 20 GDPR):** Máte právo získat osobní údaje, které jste nám poskytli, ve strukturovaném, běžně používaném a strojově čitelném formátu, a předat tyto údaje jinému správci. Toto právo se týká pouze údajů zpracovávaných **automatizovaně** (elektronicky) a na základě **Vašeho souhlasu nebo plnění smlouvy**. Typicky sem mohou spadat údaje Vašeho zákaznického účtu či objednávky. Na Vaši žádost můžeme data předat přímo jinému správci, je-li to technicky proveditelné.
- **Právo odvolat souhlas (čl. 7 odst. 3 GDPR):** Pokud je zpracování nějakých údajů založeno na Vašem **souhlasu** (např. souhlas se zasíláním newsletteru nebo se používáním cookies pro marketing), máte právo tento souhlas kdykoli **odvolat**. Odvolání souhlasu nemá zpětné účinky – zpracování provedená před odvoláním zůstávají legální, ale po odvolání již nesmíme pokračovat v daném zpracování. Souhlas můžete odvolat stejným způsobem, jakým jste jej poskytl (např. kliknutím na odhlašovací odkaz v e-mailu, změnou nastavení cookies, nebo zasláním e-mailu s žádostí o odvolání souhlasu).
- **Právo podat stížnost u dozorového úřadu:** Pokud se domníváte, že zpracováním Vašich osobních údajů porušujeme GDPR či jiné právní předpisy, máte právo podat stížnost u dozorového úřadu. Dozorovým orgánem v České republice je **Úřad pro ochranu osobních údajů** (www.uoou.cz). Budeme nicméně rádi, pokud nejprve jakékoli problémy zkusíte řešit s námi – Vaše soukromí bereme vážně a případné pochybení se budeme snažit napravit.

**Uplatnění práv:** Svá práva můžete uplatnit tak, že nás kontaktujete prostřednictvím výše uvedených kontaktních údajů (ideálně písemně e-mailem na info@devicehelp.cz). Uveďte prosím, jaké právo a v jakém rozsahu chcete využít. Na Vaši žádost odpovíme **bez zbytečného odkladu**, nejpozději však do 1 měsíce od obdržení žádosti (ve výjimečných případech lze lhůtu prodloužit na 2 měsíce, o čemž bychom Vás informovali). Upozorňujeme, že pro ověření Vaší identity můžeme vyžadovat dodatečné informace – nechceme totiž, aby se k Vašim údajům dostal někdo jiný. U některých práv Vás můžeme požádat o upřesnění žádosti (např. specifikovat, jaké informace chcete v rámci práva na přístup). V každém případě Vás budeme o vyřízení informovat. Podání žádosti je **bezplatné**. Pouze pokud by Vaše žádosti byly zjevně nedůvodné nebo nepřiměřené (např. by se často opakovaly), můžeme si výjimečně účtovat administrativní poplatek nebo odmítnout žádosti vyhovět.

## Zabezpečení osobních údajů
Správce prohlašuje, že přijal taková **technická a organizační opatření**, aby Vaše osobní údaje byly u nás v bezpečí a nemohlo dojít k jejich zneužití. Veškerá data jsou uchovávána v elektronické formě v databázích a informačních systémech, k nimž je přístup omezen hesly a šifrováním. Webové stránky využívají šifrované spojení (SSL/TLS certifikát) pro bezpečný přenos dat mezi Vaším zařízením a serverem. Na straně serverů jsou data chráněna firewally, antivirovými programy a průběžnými aktualizacemi systému. Osobní údaje v listinné podobě (pokud by existovaly např. papírové zakázkové listy) jsou uloženy v uzamčených skříních v sídle správce.

K osobním údajům mají přístup pouze oprávněné osoby, které jsou vázány **mlčenlivostí** a byly řádně poučeny o bezpečném nakládání s údaji. Každá externí firma, která pro nás zpracovává data (viz výše), se smluvně zavázala dodržovat standardy zabezpečení a chránit data stejně pečlivě jako my.

Přestože se snažíme o maximální zabezpečení dat, je třeba mít na paměti, že **žádný přenos dat po internetu ani žádné uložiště není 100% bezpečné**. Nemůžeme tak absolutně garantovat, že nemůže dojít např. k narušení bezpečnosti sofistikovaným kyberútokem. V případě jakéhokoli bezpečnostního incidentu, který by představoval riziko pro Vaše práva (např. únik dat), splníme povinnost Vás i příslušný úřad informovat dle GDPR a budeme situaci neprodleně řešit.

## Závěrečná ustanovení
Tuto Politiku zpracování osobních údajů můžeme podle potřeby **aktualizovat či měnit**, zejména pokud dojde ke změně našich procesů nebo relevantních právních předpisů. Novou verzi vydáme vždy na **webových stránkách** devicehelp.cz a v případě významných změn Vás na ni můžeme upozornit e-mailem (pokud máme Vaši adresu). Doporučujeme proto čas od času tuto stránku zkontrolovat.

Pokud s touto politikou nesouhlasíte, bohužel Vám nemůžeme poskytnout naše služby, jelikož zpracování Vašich údajů (zejména pro účely objednávky) je pro to nezbytné. Odesláním online poptávky či objednávky, registrací na webu, uzavřením servisní smlouvy, nebo i předáním zařízení k opravě osobně **stvrzujete, že jste se s touto Politikou ochrany osobních údajů seznámil(a) a že s ní souhlasíte**.

Tato verze Zásad ochrany osobních údajů je účinná od 28.06.2025.
}
        <p>{t("contentPlaceholder")}</p>
      </div>
    </div>
  )
}
